version: 2.1
executors:
  rust-executor:
    docker:
      - image: cimg/rust:1.64.0

jobs:
  test:
    executor: rust-executor
    steps:
      - checkout
      - run:
          name: Run tests
          command: cargo test --color never
      - run:
          name: Run expensive tests
          command: cargo test --color never -- --ignored --nocapture

workflows:
  rust-test-workflow:
    jobs:
      - test
