name: Rust

on: [push]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Update Rust to latest
        run: ~/.cargo/bin/rustup update

      - name: Run tests
        run: cargo test

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install Rust
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash /dev/stdin -y

      - name: Update Rust (installer may lag behind)
        run: ~/.cargo/bin/rustup update

      - name: Run tests
        run: ~/.cargo/bin/cargo test

      - name: Run expensive tests
        run: ~/.cargo/bin/cargo test -- --ignored --nocapture
